package project.android.bellringing.utilities;

public enum MethodStatus {
	
	STANDING, GO_TO_ROUNDS, ROUNDS, GO_TO_PLAYING, PLAYING, GO_TO_STAND, GO_TO_STAND_FROM_ROUNDS, GO_TO_STAND_FROM_ROUNDS_EXTRA, GO_TO_STAND_EXTRA, GO_TO_PLAYING_EXTRA, GO_TO_ROUNDS_EXTRA
	
}